name: Pip install test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nox-tests:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:${{ matrix.compiler }}
    strategy:
        matrix:
            python-version: ["3.10"]
            compiler: [gcc-10]
            build_type: [release]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install nox
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install nox
    - name: run tests
      working-directory: ./.python_package
      run: nox
